# Generated by Django 4.2.5 on 2023-10-22 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=20)),
                ('continente', models.CharField(blank=True, max_length=20, null=True)),
                ('valor', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('material', models.CharField(max_length=30)),
                ('forma', models.CharField(max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('imgfrente', models.ImageField(blank=True, null=True, upload_to='monedas')),
                ('imgdorso', models.ImageField(blank=True, null=True, upload_to='monedas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
            },
        ),
        migrations.CreateModel(
            name='FichayMedalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipodeobjeto', models.CharField(max_length=20)),
                ('pais', models.CharField(blank=True, max_length=20, null=True)),
                ('valor', models.CharField(blank=True, max_length=20, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('forma', models.CharField(blank=True, max_length=20, null=True)),
                ('imgfrente', models.ImageField(blank=True, null=True, upload_to='fichasymedallas')),
                ('imgdorso', models.ImageField(blank=True, null=True, upload_to='fichasymedallas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha/Medalla',
                'verbose_name_plural': 'Fichas/Medallas',
            },
        ),
        migrations.CreateModel(
            name='Estampilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=20)),
                ('valor', models.CharField(max_length=20)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('forma', models.CharField(blank=True, max_length=20, null=True)),
                ('imgfrente', models.ImageField(blank=True, null=True, upload_to='estampillas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estampilla',
                'verbose_name_plural': 'Estampillas',
            },
        ),
        migrations.CreateModel(
            name='Billete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=20)),
                ('continente', models.CharField(blank=True, max_length=20, null=True)),
                ('valor', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('material', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('imgfrente', models.ImageField(blank=True, null=True, upload_to='billetes')),
                ('imgdorso', models.ImageField(blank=True, null=True, upload_to='billetes')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billete',
                'verbose_name_plural': 'Billetes',
            },
        ),
    ]
